### ISSUE TITLE
OTP Code Verification

### ISSUE THREAD

**Issue by adropofliquid** [multifactor/MFKDF#4]
The OTP factor in the MFKDF library does not raise an error when an incorrect OTP code is used. Instead of returning an ‘Invalid OTP token’ error, the library proceeds and returns an incorrect key value.

**Steps to reproduce**

```
    const setup = await mfkdf.setup.key([
        await mfkdf.setup.factors.totp({secret: Buffer.from('theBESTsecret')})
    ], { size: 8 })

    const derive = await mfkdf.derive.key(setup.policy, {
        totp: mfkdf.derive.factors.totp(123456)
    })

    console.log(setup.key.toString('hex')) // -> 52947cdc1744845a
    console.log(derive.key.toString('hex')) // -> ab921b622f18950c
```

**Comment by VCNinc** [comment]
This is not a bug - MFKDF does not contain a way to verify the correctness of individual factors, as doing so would undermine the "exponential security" property whereby the entropy of all factors is combined when deriving a key.
